# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TableTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MyCheckBox(QtWidgets.QCheckBox):
    def __init__(self, nfcId):
        super().__init__()
        self.nfcId = nfcId
        self.setStyleSheet("QCheckBox::indicator { width: 20px; height: 20px;}")

    def getUID(self):
        if(self.isChecked()):
            return self.nfcId
        else :
            return False

class Ui_MainWindow(object):

    def __init__(self, data, cancelEvent):
        self.data = data
        self.checkBoxs = []
        self.targets = []
        self.cancelEvent = cancelEvent

    def delete(self):
        print('delete button')
        for box in self.checkBoxs:
            if(box.getUID() != False):
                self.targets.append(box.getUID())
        print(self.targets)
        self.targets.clear()

    def cancel(self):
        print('cancel button')
        self.cancelEvent('adminDelete_cancel')

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(780, 390)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 761, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        
        self.tableWidget.setRowCount(len(self.data))
        self.tableWidget.setColumnCount(4)

        #horizon header name
        self.tableWidget.setHorizontalHeaderLabels(["이름", "소속", "NFC ID", "삭제"])

        #resize column width to contents
        header = self.tableWidget.horizontalHeader()       
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)

        i = 0
        for current in self.data:
            nameLabel = QtWidgets.QLabel(current['name'])
            belongLabel = QtWidgets.QLabel(current['belong'])
            nfcLabel = QtWidgets.QLabel(current['nfcid'])
            checkbox = MyCheckBox(current['nfcid'])
            
            self.checkBoxs.append(checkbox)

            self.tableWidget.setCellWidget(i,0,nameLabel)
            self.tableWidget.setCellWidget(i,1, belongLabel)
            self.tableWidget.setCellWidget(i,2, nfcLabel)

            checkBoxCellWidget = QtWidgets.QWidget()
            lay_out = QtWidgets.QHBoxLayout(checkBoxCellWidget)
            lay_out.addWidget(checkbox)
            lay_out.setAlignment(QtCore.Qt.AlignCenter)
            lay_out.setContentsMargins(0,0,0,0)
            checkBoxCellWidget.setLayout(lay_out)
            self.tableWidget.setCellWidget(i,3, checkBoxCellWidget)

            i+=1


        self.tableWidget.setObjectName("tableWidget")
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.cancel) #Event
        self.horizontalLayout.addWidget(self.pushButton_2)

        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.delete) #Event
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 780, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "취소하기"))
        self.pushButton.setText(_translate("MainWindow", "삭제하기"))

if __name__ == "__main__":
    import sys
    
    data = [
        {'name': '송송', 'nfcid': '12345678', 'belong': '숭실대 IT대 융특'},
        {'name': '슝슝', 'nfcid': '123456789', 'belong': '숭실대 IT대 소프트웨어'},
    ]

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow(data)
    ui.setupUi(MainWindow)
    MainWindow.show()

    sys.exit(app.exec())
